liip_imagine:
  driver: "gd"
  resolvers:
    default:
      web_path:
        cache_prefix: cache # media/cache
  filter_sets:
    avatar_tiny:
      quality: 90
      filters:
        auto_rotate: ~
        fixed:
          width: 32
          height: 32
        strip: ~
      format: jpeg

    avatar_medium:
      quality: 90
      filters:
        auto_rotate: ~
        fixed:
          width: 128
          height: 128
        strip: ~
      format: jpeg

    avatar_large:
      quality: 90
      filters:
        auto_rotate: ~
        fixed:
          width: 256
          height: 256
        strip: ~
      format: jpeg