vich_uploader:
  db_driver: orm

  mappings:
    profile_images:
      uri_prefix: /uploads/profiles
      upload_destination: '%kernel.project_dir%/public/uploads/profiles'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      delete_on_update: true
      delete_on_remove: true
