version: '3.7'
services:
  traefik:
    image: traefik:latest
    container_name: traefik_udemy
    ports:
      - "80:80"
      - "443:443"
    #      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/conf/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./docker/conf/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./docker/certs/:/etc/certs:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.test`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=traefik@docker"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  web:
    container_name: php-udemy-web
    image: nginx:alpine
    #    ports:
    #      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`php-udemy.test`) || Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=https"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.service=web@docker"
      - "traefik.http.services.web.loadbalancer.server.port=80"
  php:
    container_name: php-udemy-php
    build:
      context: ./docker/dockerfiles
      dockerfile: php.Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
        UNAME: ${HOST_UNAME}
        USERNAME: ${LOGIN_USERNAME}
    volumes:
      - ./:/var/www/html
      - ./docker/conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  #      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  db:
    container_name: php-udemy-db
    image: mariadb:11.1
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: db
      MARIADB_ROOT_PASSWORD: taynamayna
    volumes:
      - db:/var/lib/mysql
  #    ports:
  #      - "3306:3306"
  mailcatcher:
    container_name: php-udemy-mailcatcher
    image: dockage/mailcatcher:0.9.0
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailcatcher.rule=Host(`php-udemy-mailcatcher.test`)"
      - "traefik.http.routers.mailcatcher.entrypoints=https"
      - "traefik.http.routers.mailcatcher.tls=true"
      - "traefik.http.routers.mailcatcher.service=mailcatcher@docker"
      - "traefik.http.services.mailcatcher.loadbalancer.server.port=1080"
volumes:
  db:

